[project]
name = "askpanda_atlas"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
  "requests>=2.0",
]

[project.entry-points."bamboo.tools"]
"atlas.task_status" = "askpanda_atlas.task_status:panda_task_status_tool"

[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["askpanda_atlas"]
